//! Build script that auto-discovers and compiles Waltzing template libraries.
//!
//! Libraries are discovered by scanning `libraries/` for directories containing
//! a `waltzing-*.toml` or `library.toml` manifest file.

use serde::Deserialize;
use std::collections::HashMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Deserialize)]
struct LibraryManifest {
    library: LibraryInfo,
    #[serde(default)]
    tailwind: Option<TailwindConfig>,
    #[serde(default)]
    alpine: Option<AlpineConfig>,
    #[serde(default)]
    components: HashMap<String, ComponentEntry>,
    #[serde(default)]
    layouts: HashMap<String, ComponentEntry>,
}

#[derive(Debug, Deserialize)]
struct LibraryInfo {
    name: String,
    version: String,
    description: String,
    #[serde(default)]
    repository: Option<String>,
    #[serde(default)]
    license: Option<String>,
}

#[derive(Debug, Deserialize)]
struct TailwindConfig {
    #[serde(default)]
    plugins: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct AlpineConfig {
    #[serde(default)]
    plugins: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct ComponentEntry {
    path: String,
    #[serde(default)]
    deps: Vec<String>,
}

#[derive(Debug)]
struct DiscoveredLibrary {
    dir_name: String,
    manifest: LibraryManifest,
    manifest_path: String,
}

fn discover_libraries() -> Vec<DiscoveredLibrary> {
    let libraries_dir = Path::new("libraries");
    let mut libraries = Vec::new();

    if !libraries_dir.exists() {
        println!("cargo:warning=No libraries/ directory found");
        return libraries;
    }

    for entry in fs::read_dir(libraries_dir).expect("Failed to read libraries/") {
        let entry = entry.expect("Failed to read directory entry");
        let path = entry.path();

        if !path.is_dir() {
            continue;
        }

        let dir_name = path.file_name().unwrap().to_string_lossy().to_string();

        // Look for library.toml or {dir_name}.toml
        let manifest_path = if path.join("library.toml").exists() {
            path.join("library.toml")
        } else if path.join(format!("{}.toml", dir_name)).exists() {
            path.join(format!("{}.toml", dir_name))
        } else {
            println!(
                "cargo:warning=Skipping {}: no library.toml or {}.toml found",
                dir_name, dir_name
            );
            continue;
        };

        let manifest_content =
            fs::read_to_string(&manifest_path).expect("Failed to read manifest");

        match toml::from_str::<LibraryManifest>(&manifest_content) {
            Ok(manifest) => {
                println!("cargo:rerun-if-changed={}", manifest_path.display());
                libraries.push(DiscoveredLibrary {
                    dir_name,
                    manifest,
                    manifest_path: manifest_path.to_string_lossy().to_string(),
                });
            }
            Err(e) => {
                println!(
                    "cargo:warning=Failed to parse {}: {}",
                    manifest_path.display(),
                    e
                );
            }
        }
    }

    libraries
}

fn compile_library(library: &DiscoveredLibrary) {
    let lib_dir = Path::new("libraries").join(&library.dir_name);

    println!(
        "cargo:warning=Discovered library: {} ({})",
        library.manifest.library.name,
        lib_dir.display()
    );

    // TODO: Compile templates when waltzing crate is available
    // waltzing::compile_templates(
    //     lib_dir.to_str().unwrap(),
    //     &format!("src/generated/{}", library.dir_name),
    // )
    // .expect(&format!(
    //     "Failed to compile templates for {}",
    //     library.manifest.library.name
    // ));

    // Watch for changes in the library directory
    println!("cargo:rerun-if-changed={}", lib_dir.display());

    // Watch all .wtz files
    for entry in walkdir::WalkDir::new(&lib_dir)
        .into_iter()
        .filter_map(|e| e.ok())
    {
        let path = entry.path();
        if path.extension().map_or(false, |ext| ext == "wtz") {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
}

fn generate_libraries_module(libraries: &[DiscoveredLibrary]) {
    let out_dir = Path::new("src/generated");
    fs::create_dir_all(out_dir).expect("Failed to create src/generated");

    let mut code = String::new();
    code.push_str("//! Auto-generated module containing discovered libraries.\n");
    code.push_str("//! DO NOT EDIT - regenerated by build.rs\n\n");

    code.push_str("use serde::Serialize;\n\n");

    code.push_str("#[derive(Debug, Clone, Serialize)]\n");
    code.push_str("pub struct Library {\n");
    code.push_str("    pub id: &'static str,\n");
    code.push_str("    pub name: &'static str,\n");
    code.push_str("    pub version: &'static str,\n");
    code.push_str("    pub description: &'static str,\n");
    code.push_str("    pub component_count: usize,\n");
    code.push_str("}\n\n");

    code.push_str("pub const LIBRARIES: &[Library] = &[\n");

    for lib in libraries {
        let component_count = lib.manifest.components.len() + lib.manifest.layouts.len();
        code.push_str(&format!(
            "    Library {{\n        id: \"{}\",\n        name: \"{}\",\n        version: \"{}\",\n        description: \"{}\",\n        component_count: {},\n    }},\n",
            lib.dir_name,
            lib.manifest.library.name,
            lib.manifest.library.version,
            lib.manifest.library.description.replace("\"", "\\\""),
            component_count,
        ));
    }

    code.push_str("];\n\n");

    // Generate submodule declarations
    for lib in libraries {
        let module_name = lib.dir_name.replace("-", "_");
        code.push_str(&format!("pub mod {};\n", module_name));
    }

    fs::write(out_dir.join("mod.rs"), code).expect("Failed to write mod.rs");

    // Generate placeholder module file for each library
    for lib in libraries {
        let module_name = lib.dir_name.replace("-", "_");
        let module_path = out_dir.join(format!("{}.rs", module_name));

        // Generate component list
        let components: Vec<&String> = lib.manifest.components.keys().collect();
        let layouts: Vec<&String> = lib.manifest.layouts.keys().collect();

        let mut lib_code = String::new();
        lib_code.push_str(&format!(
            "//! Generated module for {} library.\n",
            lib.manifest.library.name
        ));
        lib_code.push_str("//! DO NOT EDIT - regenerated by build.rs\n\n");

        lib_code.push_str("/// List of components in this library\n");
        lib_code.push_str("pub const COMPONENTS: &[&str] = &[\n");
        for comp in &components {
            lib_code.push_str(&format!("    \"{}\",\n", comp));
        }
        lib_code.push_str("];\n\n");

        lib_code.push_str("/// List of layouts in this library\n");
        lib_code.push_str("pub const LAYOUTS: &[&str] = &[\n");
        for layout in &layouts {
            lib_code.push_str(&format!("    \"{}\",\n", layout));
        }
        lib_code.push_str("];\n\n");

        lib_code.push_str("// TODO: When waltzing crate is available, compiled templates will be included here\n");
        lib_code.push_str("// pub mod components { ... }\n");
        lib_code.push_str("// pub mod layouts { ... }\n");

        fs::write(module_path, lib_code).expect("Failed to write library module");
    }
}

fn main() {
    println!("cargo:rerun-if-changed=libraries");
    println!("cargo:rerun-if-changed=build.rs");

    let libraries = discover_libraries();

    println!(
        "cargo:warning=Discovered {} libraries",
        libraries.len()
    );

    for library in &libraries {
        compile_library(library);
    }

    generate_libraries_module(&libraries);
}
